/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ExtendedAsciiPlotPolygon } from "./ExtendedAsciiPlotPolygon";

export { ExtendedAsciiPlotPolygon__factory } from "./factories/ExtendedAsciiPlotPolygon__factory";
